[workspace]
members = [
    "AOL2/anchor",
    "AOL2/p2p",
    "AOL2/truth-engine/examples",
    "AOL2/truth-engine/qssm-api",
    "AOL2/truth-engine/qssm-cli",
    "AOL2/truth-engine/qssm-core",
    "AOL2/truth-engine/qssm-entropy",
    "AOL2/truth-engine/qssm-gadget",
    "AOL2/truth-engine/qssm-le",
    "AOL2/truth-engine/qssm-local-prover",
    "AOL2/truth-engine/qssm-local-verifier",
    "AOL2/truth-engine/qssm-ms",
    "AOL2/truth-engine/qssm-proofs",
    "AOL2/truth-engine/qssm-templates",
    "AOL2/truth-engine/qssm-utils",
    "desktop/src-tauri",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "GPL-2.0-only"
repository = "https://github.com/peavey2787/mssq-rs"

[workspace.dependencies]
accelerometer = "0.12"
argon2 = "0.5"
blake3 = "1.5"
futures = "0.3"
hex = "0.4"
libp2p = "0.56"
maxminddb = "0.28.1"
rand = "0.8"
rayon = "1.10"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
smallvec = "1.13"
thiserror = "1.0"
tokio = { version = "1", features = ["fs", "io-util", "macros", "rt-multi-thread", "signal", "sync", "time"] }
ureq = "3.3.0"

p2p-net = { package = "p2p", path = "AOL2/p2p" }
qssm-entropy = { path = "AOL2/truth-engine/qssm-entropy" }
qssm-gadget = { path = "AOL2/truth-engine/qssm-gadget", version = "=1.1.0" }
qssm-le = { path = "AOL2/truth-engine/qssm-le", version = "=1.0.0" }
qssm-ms = { path = "AOL2/truth-engine/qssm-ms", version = "=1.0.0" }
qssm-utils = { path = "AOL2/truth-engine/qssm-utils", version = "=1.0.0" }

[profile.dev]
split-debuginfo = "unpacked"

[patch.crates-io]
kaspa-wallet-core = { path = "vendor/kaspa-wallet-core" }
workflow-node = { path = "vendor/workflow-node" }
