[package]
name = "desktop"
version = "0.1.0"
description = "Tauri: AOL2 command center and identity manager"
authors = ["QSSM"]
edition.workspace = true
license.workspace = true
publish = false

[lib]
name = "desktop_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
blake3 = { workspace = true }
hex = { workspace = true }
rand = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "time"] }
ureq = { workspace = true, features = ["json"] }
maxminddb.workspace = true
bip39 = "2.1"
argon2 = { workspace = true }
zeroize = "1.8"
aes-gcm = "0.10"
libp2p = { workspace = true }
p2p-net = { workspace = true, optional = true }
qssm-entropy = { workspace = true, optional = true }
qssm-utils.workspace = true

[features]
default = ["full-stack"]
identity-only = ["dep:qssm-entropy"]
transport-only = []
full-stack = ["identity-only", "transport-only", "dep:p2p-net"]
